// Copyright (c) 2026 Zhengyi Miao (github.com/myoozy)

#pragma once

#include "CoreMinimal.h"
#include "VehicleUtilities.h"
#include "VehicleSuspensionStructs.generated.h"

UENUM(BlueprintType)
enum class EVehicleIndependentSuspensionType : uint8
{
	StraightLine		UMETA(ToolTip = "Only moves up and down. This can simulate fork suspension like the front suspension of a motorbike, but with camber and toe setup."),
	Macpherson			UMETA(ToolTip = "Simplified macpherson suspension. It has one control arm and one strut. The rotation of the wheel knuckle or the wheel hub will be automatically calculated."),
	DoubleWishbone		UMETA(ToolTip = "Simplified wishbone suspension. It only has one control arm and one strut. The changes of the camber/toe/caster are defined by user's float curves.")
};

UENUM(BlueprintType)
enum class EVehicleSuspensionRayCastMode : uint8
{
	LineTrace					UMETA(ToolTip = "The fastest raycast mode. The Line Trace will start at outer side of the wheel."),
	SphereTrace					UMETA(ToolTip = "Using sphere(radius is wheel radius) instead of line trace. If impact point is wrong(e.g. hit the wall), it will do sphere trace again."),
	BoxTrace					UMETA(ToolTip = "Using a box (with 45deg of pitch displacement) to trace."),
	SphereTraceNoRefinement		UMETA(ToolTip = "Using a small sphere to trace(radius = min(WheelRadius, WheelWidth * 0.5)."),
	MultiSphereTrace			UMETA(ToolTip = "Similar to sphere trace. First it uses sphere trace. If the result is not valid(e.g. hit the wall), it will do box trace(to roughly check if there're obstacles). If box trace did hit, then it will do multi-sphere trace. The performance can be really bad in worst case. But normally the same as SphereTrace. Some times not very stable.")
};

UENUM(BlueprintType)
enum class EVehicleForceApplicationPoint : uint8
{
	ImpactPoint			UMETA(ToolTip = "Apply suspension and tire force at the impact point of the ray-casting"),
	WheelCenter			UMETA(ToolTip = "Apply suspension and tire force at the center of wheel, which causes less pitch and roll")
};

/*
* A simple wishbone.
* MountLocation: relative to wheel component
* RotationAxis: relative to wheel component, unnormalized
* Length: unit: centimeter
*/
USTRUCT(BlueprintType)
struct KINETIFORGE_API FVehicleSuspensionWishboneConfig
{
	GENERATED_BODY()

	/**
	* relative to the wheel component.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector3f MountLocalLocation = FVector3f(0.f);

	/**
	* relative to the wheel component.
	* This is not normalized, not a unit vector.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector3f RotationLocalAxis = FVector3f(1.f, 0.f, 0.f);

	/**
	* Unit: cm
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float Length = 50.f;
};

USTRUCT(BlueprintType)
struct KINETIFORGE_API FVehicleSuspensionKinematicsConfig
{
	GENERATED_BODY()

	/**
	* Type of suspension. Only supports independent suspension. 
	* (Solid axle is only supported when the wheels are generated by an axle)
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EVehicleIndependentSuspensionType SuspensionType = EVehicleIndependentSuspensionType::Macpherson;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EVehicleSuspensionRayCastMode RayCastMode = EVehicleSuspensionRayCastMode::LineTrace;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TEnumAsByte<ECollisionChannel> TraceChannel = ECollisionChannel::ECC_WorldDynamic;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EVehicleForceApplicationPoint LocationToApplyForce = EVehicleForceApplicationPoint::ImpactPoint;

	/**
	* The location of the top mount relative to the WheelComponent.
	* NOTE: This is LOCAL to the wheel component's origin.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector3f TopMountLocalLocation = FVector3f(0.f, 45.f, 35.f);

	/**
	* Unit: cm. The maximum compressible traveling distance of the strut.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float Stroke = 20.f;

	/**
	* Unit: cm. The physical length of the strut when fully compressed (Bump stop).
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float MinStrutLength = 40.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (EditCondition = "SuspensionType != ESuspensionType::StraightLine"))
	FVehicleSuspensionWishboneConfig LowerWishbone =
		FVehicleSuspensionWishboneConfig(FVector3f(0.f, 0.f, -10.f), FVector3f(1.f, 0.f, 0.f), 50.f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (EditCondition = "SuspensionType == ESuspensionType::DoubleWishbone"))
	FVehicleSuspensionWishboneConfig UpperWishbone =
		FVehicleSuspensionWishboneConfig(FVector3f(0.f, 0.f, 10.f), FVector3f(1.f, 0.f, 0.f), 47.f);

	/**
	* Unit: cm
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (EditCondition = "SuspensionType == ESuspensionType::DoubleWishbone"))
	float KnuckleLength = 30.f;

	/**
	* The relative location of the wheel hub FROM the lower ball joint.
	* This defines the shape of the upright/knuckle rigid body.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector3f HubOffsetFromLowerJoint = FVector3f(0.f, 5.f, 10.f);

	/**
	* The static angular offset of the wheel spinning axis relative to the upright.
	* Determines base camber and toe.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FRotator3f StaticSpindleRotation = FRotator3f(0.f, 0.f, 5.f);

	/**
	* X: SuspensionCompressionRatio; Y:CamberGain; Only enabled when the suspension type is double-wishbone
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* CamberCurve = nullptr;

	/**
	* X: SuspensionCompressionRatio; Y:ToeGain; Only enabled when the suspension type is double-wishbone
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* ToeCurve = nullptr;

	/**
	* X: SuspensionCompressionRatio; Y:CasterGain; Only enabled when the suspension type is double-wishbone
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* CasterCurve = nullptr;

	/**
	* Controls suspension resistance to compression under BRAKING (Front wheels mostly).
	* X-Axis: Suspension Compression (0 = Fully Extended, 1 = Fully Compressed).
	* Y-Axis: Counter-Force Ratio (0 = Natural Dive, 1 = No Dive/Flat, >1 = Nose Lift).
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* AntiDiveCurve = nullptr;

	/**
	* Controls suspension resistance to compression under ACCELERATING (Rear wheels mostly).
	* X-Axis: Suspension Compression (0 = Fully Extended, 1 = Fully Compressed).
	* Y-Axis: Counter-Force Ratio (0 = Natural Squat, 1 = No Squat/Flat, >1 = Lift/Anti-Gravity).
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* AntiSquatCurve = nullptr;

	/**
	* Controls suspension resistance to compression under CORNERING.
	* X-Axis: Suspension Compression (0 = Fully Extended, 1 = Fully Compressed).
	* Y-Axis: Counter-Force Ratio (0 = Natural Roll, 1 = No Roll/Flat, >1 = Roll in opposite direction).
	* 
	* Don't set this too high because in reallife most of the anti-roll effect comes from the anti-roll bar / swaybar.
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* AntiRollCurve = nullptr;

	/**
	* Motion ratio of the spring. This can simulate push/pull rod suspension (maybe).
	*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UCurveFloat* SpringMotionRatioCurve = nullptr;
};

USTRUCT(BlueprintType)
struct KINETIFORGE_API FVehicleSuspensionSpringConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float SpringStiffness = 350.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float CompressionDamping = 0.4;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float ReboundDamping = 0.6;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bUseDampingRatio = true;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0"))
	float SpringPreload = 0.f;			//N
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0", ClampMax = "1.0", UIMin = "0.0", UIMax = "1.0", ToolTip = "Scales the stiffness of the auxiliary spring to prevent ground penetration at full suspension compression."))
	float BottomOutStiffness = 0.8f;
};

USTRUCT()
struct KINETIFORGE_API FVehicleSuspensionCachedLUTs
{
	GENERATED_BODY()

	FVehicleLUT<16> CamberCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> ToeCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> CasterCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> AntiDiveCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> AntiSquatCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> AntiRollCurve = FVehicleLUT<16>(0.f);
	FVehicleLUT<16> MotionRatioCurve = FVehicleLUT<16>(1.f);
};

USTRUCT(BlueprintType, meta = (ToolTip = "A simplified HitResult"))
struct KINETIFORGE_API FVehicleSuspensionHitResult
{
	GENERATED_BODY()

	UPROPERTY()
	TWeakObjectPtr<UPhysicalMaterial> PhysMaterial = nullptr;
	UPROPERTY()
	TWeakObjectPtr<UPrimitiveComponent> Component = nullptr;
	UPROPERTY()
	FName BoneName = NAME_None;
	UPROPERTY()
	bool bBlockingHit = false;
	UPROPERTY()
	FVector TraceStart = FVector(0.f);
	UPROPERTY()
	FVector TraceEnd = FVector(0.f);
	UPROPERTY()
	FVector Location = FVector(0.f);
	UPROPERTY()
	FQuat4f TraceRot = FQuat4f(0.f);
};

USTRUCT(BlueprintType, meta = (ToolTip = "suspension state in simulation"))
struct KINETIFORGE_API FVehicleSuspensionSimState
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Movement")
	float SteeringAngle = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float SuspensionCurrentLength = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float SprungMass = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float ForceAlongImpactNormal = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float AntiPitchScale = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float AntiRollScale = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f WheelWorldRightVector = FVector3f(0.f); 
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f HubChassisLocation = FVector3f(0.f);	
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FQuat4f HubChassisRotation = FQuat4f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f TopMountChassisLocation = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f UpperBallJointChassisLocation = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f LowerBallJointChassisLocation = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f SteerAxisChassisDirection = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector3f ImpactWorldVelocity = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector3f ImpactWorldNormal = FVector3f(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector ImpactWorldLocation = FVector(0.f);
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	float ImpactFriction = 1.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "State")
	bool bIsRightWheel = true;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	bool bHitGround = true;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	bool bValidKinematicsConfig = true;
};

USTRUCT(BlueprintType, meta = (ToolTip = "Suspension context (temporary cache) in simulation"))
struct KINETIFORGE_API FVehicleSuspensionSimContext
{
	GENERATED_BODY()

	// [原 WheelPos] 这是一个乘数 (1 或 -1)，叫 Sign/Multiplier 更准确，Pos 会和 Position 混淆
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Config")
	float WheelSideSign = 1.f;

	// [原 PhysicsDelatTime] 修复了拼写错误 Delat -> Delta
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Time")
	float PhysicsDeltaTime = 0.00833333f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	float RayCastLength = 1.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast", meta = (ToolTip = "The smoothened hit distance from hit result (smoothened using spring and damper)"))
	float HitDistance = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float SuspensionCurrentLength = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float SuspensionExtensionRatio = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Movement")
	float SteeringAngle = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Config")
	float ValidPreload = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float SwaybarForce = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float SuspensionForce = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float ForceAlongImpactNormal = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float SprungMass = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float WorldGravityZ = 9.8f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	float ImpactFriction = 1.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float AntiPitchScale = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	float AntiRollScale = 0.f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Force")
	float JackingForce = 0.f;

	// [原 HubToLowerArmEnd] 明确指出它是车身空间的偏移向量
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f HubOffsetFromLowerJointChassis = FVector3f(0.f);

	// [原 LowerWishboneEnd] 统一使用 BallJoint + 坐标系
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f LowerBallJointChassisLocation = FVector3f(0.f);

	// [原 UpperWishboneEnd]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f UpperBallJointChassisLocation = FVector3f(0.f);

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f LowerPivotChassisLocation = FVector3f(0.f);

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f UpperPivotChassisLocation = FVector3f(0.f);

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f LowerWishboneChassisAxis = FVector3f::ForwardVector;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f UpperWishboneChassisAxis = FVector3f::ForwardVector;

	// [原 TopMountRelativePos]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f TopMountChassisLocation = FVector3f(0.f);

	// [原 StrutRelativeDirection]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry", meta = (ToolTip = "The strut direction in Chassis space"))
	FVector3f StrutChassisDirection = FVector3f(0.f);

	// [原 KinpinRelative] 修复拼写 Kinpin -> SteerAxis
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector3f SteerAxisChassisDirection = FVector3f(0.f);

	// [原 RayCastStartRelative]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector3f RayCastStartChassisLocation = FVector3f(0.f);

	// [原 ImpactPointWorldVelocity]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Movement")
	FVector3f ImpactWorldVelocity = FVector3f(0.f);

	// [原 LowerWishboneAxisRot] 明确它是相对于车轮组件的 Local 旋转
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FQuat4f LowerWishboneLocalRotation = FQuat4f::Identity;

	// [原 WheelRightVector]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector WheelWorldRightVector = FVector(0.f);

	// [原 RayCastStartWorld]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector RayCastStartWorldLocation = FVector(0.f);

	// [原 RayCastEndWorld]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FVector RayCastEndWorldLocation = FVector(0.f);

	// [原 StrutDirection]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector StrutWorldDirection = FVector(0.f);

	// [原 HubWorldPos]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FVector HubWorldLocation = FVector(0.f);

	// [原 RayCastTransform]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FTransform RayCastWorldTransform = FTransform(FQuat(0.f));

	// [原 ChassisWorldTransform] 终于可以彻底正名为 Chassis 了
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FTransform ChassisWorldTransform = FTransform(FQuat(0.f));

	// [原 RelativeTransform] 极其危险的命名！明确改为组件到车身的 Transform
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FTransform3f WheelCompToChassisTransform = FTransform3f(FQuat4f(0.f));

	// [原 HubRelativeTransform]
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Geometry")
	FTransform3f HubChassisTransform = FTransform3f(FQuat4f(0.f));

	// [原 HitStruct] 虚幻原生喜欢叫 HitResult
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	FHitResult HitResult = FHitResult();

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	bool bHitGround = true;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	bool bRayCastRefined = false;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "RayCast")
	bool bValidKinematicsConfig = true;
};