[CoreRedirects]

; --- AxleAssemblyComponent ---
+PropertyRedirects=(OldName="VehicleAxleAssemblyComponent.WheelConfig",NewName="VehicleAxleAssemblyComponent.WheelClass")
+PropertyRedirects=(OldName="VehicleAxleAssemblyComponent.DifferentialConfig",NewName="VehicleAxleAssemblyComponent.DifferentialClass")

; --- DriveAssemblyComponent ---
+StructRedirects=(OldName="AxleAssemblyConfig",NewName="VehicleAxleSpawnTemplate")

+PropertyRedirects=(OldName="VehicleDriveAssemblyComponent.AxleConfigs",NewName="VehicleDriveAssemblyComponent.AxleTemplates")
+PropertyRedirects=(OldName="VehicleDriveAssemblyComponent.EngineConfig",NewName="VehicleDriveAssemblyComponent.EngineClass")
+PropertyRedirects=(OldName="VehicleDriveAssemblyComponent.ClutchConfig",NewName="VehicleDriveAssemblyComponent.ClutchClass")
+PropertyRedirects=(OldName="VehicleDriveAssemblyComponent.GearboxConfig",NewName="VehicleDriveAssemblyComponent.GearboxClass")
+PropertyRedirects=(OldName="VehicleDriveAssemblyComponent.TransferCaseConfig",NewName="VehicleDriveAssemblyComponent.TransferCaseClass")

; 1. WheelClassOverride
+PropertyRedirects=(OldName="AxleAssemblyConfig.WheelOverride",NewName="VehicleAxleSpawnTemplate.WheelClassOverride")
+PropertyRedirects=(OldName="VehicleAxleSpawnTemplate.WheelOverride",NewName="VehicleAxleSpawnTemplate.WheelClassOverride")

; 2. DifferentialClassOverride
+PropertyRedirects=(OldName="AxleAssemblyConfig.DifferentialOverride",NewName="VehicleAxleSpawnTemplate.DifferentialClassOverride")
+PropertyRedirects=(OldName="VehicleAxleSpawnTemplate.DifferentialOverride",NewName="VehicleAxleSpawnTemplate.DifferentialClassOverride")

; 3. AxleClass
+PropertyRedirects=(OldName="AxleAssemblyConfig.AxleConfig",NewName="VehicleAxleSpawnTemplate.AxleClass")
+PropertyRedirects=(OldName="VehicleAxleSpawnTemplate.AxleConfig",NewName="VehicleAxleSpawnTemplate.AxleClass")

; --- WheelComponent ---
+PropertyRedirects=(OldName="VehicleSuspensionKinematicsConfig.TopMountLocalPosition",NewName="VehicleSuspensionKinematicsConfig.TopMountLocalLocation")
+PropertyRedirects=(OldName="VehicleSuspensionKinematicsConfig.HubOffsetFromLowerJointPosition",NewName="VehicleSuspensionKinematicsConfig.HubOffsetFromLowerJointLocation") 
+PropertyRedirects=(OldName="VehicleSuspensionKinematicsConfig.SpindleMountRotation",NewName="VehicleSuspensionKinematicsConfig.StaticSpindleRotation")
+PropertyRedirects=(OldName="VehicleSuspensionSpringConfig.CompressionDampingRatio",NewName="VehicleSuspensionSpringConfig.CompressionDamping")
+PropertyRedirects=(OldName="VehicleSuspensionSpringConfig.ReboundDampingRatio",NewName="VehicleSuspensionSpringConfig.ReboundDamping")

+EnumRedirects=(OldName="ESuspensionType",NewName="EVehicleIndependentSuspensionType")
+EnumRedirects=(OldName="ESuspensionRayCastMode",NewName="EVehicleSuspensionRayCastMode")
+EnumRedirects=(OldName="EPositionToApplyForce",NewName="EVehicleForceApplicationPoint")

; --- Physics State ---
+StructRedirects=(OldName="/Script/KinetiForge.VehicleSuspensionSimData", NewName="/Script/KinetiForge.VehicleSuspensionSimState")
+StructRedirects=(OldName="/Script/KinetiForge.VehicleWheelSimData", NewName="/Script/KinetiForge.VehicleWheelSimState")
+StructRedirects=(OldName="/Script/KinetiForge.VehicleEngineSimData", NewName="/Script/KinetiForge.VehicleEngineSimState")
+StructRedirects=(OldName="/Script/KinetiForge.VehicleClutchSimData", NewName="/Script/KinetiForge.VehicleClutchSimState")
+EnumRedirects=(OldName="/Script/KinetiForge.VehicleEngineState", NewName="/Script/KinetiForge.VehicleEngineOperationMode")



[/Script/Engine.PhysicsSettings]
bTickPhysicsAsync=True
AsyncFixedTimeStepSize=0.008333
bSubstepping=False
bSubsteppingAsync=False
MaxSubstepDeltaTime=0.016667
PhysicErrorCorrection=(PingExtrapolation=0.100000,PingLimit=100.000000,ErrorPerLinearDifference=1.000000,ErrorPerAngularDifference=1.000000,MaxRestoredStateError=1.000000,MaxLinearHardSnapDistance=400.000000,PositionLerp=0.000000,AngleLerp=0.000000,LinearVelocityCoefficient=100.000000,AngularVelocityCoefficient=10.000000,ErrorAccumulationSeconds=0.500000,ErrorAccumulationDistanceSq=15.000000,ErrorAccumulationSimilarity=100.000000)
SyncSceneSmoothingFactor=0.000000
PhysicsPrediction=(bEnablePhysicsPrediction=False,bEnablePhysicsResimulation=False,ResimulationErrorThreshold=10.000000,MaxSupportedLatencyPrediction=1000.000000)
MaxPhysicsDeltaTime=0.033333
